[package]
name = "apc-sales"
version = "0.0.0"
authors = ["Angry Penguins Colony"]
edition = "2021"
publish = false

[lib]
path = "src/main.rs"

[dependencies.multiversx-sc]
version = "0.39.5"

[dev-dependencies.multiversx-sc-scenario]
version = "0.39.5"

[dev-dependencies]
num-bigint = "0.4.2"
